# Site settings
title: "Marcel Champagne"
email: champagn@grinnell.edu
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://scontent-ord1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11224471_10207942379623964_4446487529219587198_n.jpg?oh=0af200956b2807ff28d37db89827de40&oe=568AE458"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/mnaircckel/mnaircckel.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: https://github.com/mnaircckel
linkedin_link: https://www.linkedin.com/pub/marcel-champagne/104/649/30a
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://github.com/mnaircckel\">Marcel Champagne</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
