# Site settings
title: "Marcel Champagne"
email: champagn@grinnell.edu
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://mnaircckel.github.io/"
title_description: "Hello, my name is Marcel Champagne. I am currently a computer science student at Grinnell College."
title_image: "https://scontent-ord1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11224471_10207942379623964_4446487529219587198_n.jpg?oh=0af200956b2807ff28d37db89827de40&oe=568AE458"
google_analytics: ""
disqus_account: 
github_repository: https://github.com/mnaircckel/mnaircckel.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: mnaircckel
linkedin_link: https://www.linkedin.com/pub/marcel-champagne/104/649/30a
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://github.com/mnaircckel\">Marcel Champagne</a>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
